### ISSUE TITLE
Avoid duplicates unique entry

### ISSUE THREAD

**Issue by mydnic** [martinbean/laravel-sluggable-trait#1]
Hello and thank you for this very cool package !!

I'm not sure what is the best way to do it, but it would be pretty cool if we can check if the generated Slug already exists in the Database.
Mainly because the Slug column is often unique.

So if I save two entries in the database with the same title, the second entry will have a different slug, like:

my-cool-article
my-cool-article-1

What do you think ?

**Comment by martinbean** [comment]
Thanks, @mydnic. This is indeed on the roadmap. I’ll add in version 0.3.0 of the package.

**Comment by sparkeleven** [comment]
@mydnic check out my additions to the package that handle uniqueness of slugs and a couple of other things... https://github.com/sparkeleven/laravel-sluggable-trait

**Comment by martinbean** [comment]
Just pushed 0.3.0, bumping this to 0.4.0.

**Comment by umefarooq** [comment]
i already make it can i send you pull request?
