### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by morgothx** [martinbean/laravel-sluggable-trait#6]
Hi. Thank you for the trait it works great.

I want it to work when updating a model too not just in save.

I override the bootSluggable on my model and add the code below to the method. It works fine but I have to do this manually on every model that i want to update the slug.

static::updating(function (Model $model)
        {
            $model->setSlug(Str::slug($model->getSluggableString()));
        });

Thank you.

Sorry for my bad english

**Comment by martinbean** [comment]
@morgothx The trait fires on the Eloquent `saving` event, so should fire when both when a model is created _and_ updated. Are you not seeing this behaviour?

**Comment by morgothx** [comment]
Hi, thank you for the reply.

No The slug is updated only when a new register was created, but not when is updated. 
uhmm Now i think that the `setSlug()` is only called when the field slug is empty, can this be the cause? 

```php
if (empty($model->getSlug())) {
```

**Comment by martinbean** [comment]
@morgothx Yeah, that looks like an issue. Good spot!

I’ll push a fix as soon as I can.

**Comment by morgothx** [comment]
Thank you, I forget to close this
